CREATE TABLE "ROOT"."ACCESS_STATISTICS"
(
"AS_ID" VARCHAR(32) NOT NULL,
"IP" VARCHAR(64),
"COUNTS" INT DEFAULT 0,
"EXTEND1" INT,
"EXTEND2" VARCHAR(255),
"EXTEND3" VARCHAR(255),
"CREATER" VARCHAR(10) DEFAULT 'SMS',
"CREATE_TIME" VARCHAR(32),
"MODIFIER" VARCHAR(10) DEFAULT 'SMS',
"OPERTE_TIME" VARCHAR(32),
"YN" TINYINT DEFAULT 1,
NOT CLUSTER PRIMARY KEY("AS_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."ACCESS_STATISTICS" IS '客户端IP访问统计表';
COMMENT ON COLUMN "ROOT"."ACCESS_STATISTICS"."AS_ID" IS '主键';
COMMENT ON COLUMN "ROOT"."ACCESS_STATISTICS"."COUNTS" IS '访问次数';
COMMENT ON COLUMN "ROOT"."ACCESS_STATISTICS"."CREATE_TIME" IS '操作时间';
COMMENT ON COLUMN "ROOT"."ACCESS_STATISTICS"."CREATER" IS '操作人';
COMMENT ON COLUMN "ROOT"."ACCESS_STATISTICS"."MODIFIER" IS '修改人';
COMMENT ON COLUMN "ROOT"."ACCESS_STATISTICS"."OPERTE_TIME" IS '修改时间';
COMMENT ON COLUMN "ROOT"."ACCESS_STATISTICS"."YN" IS '是否有效，1=有效，0=无效';


CREATE OR REPLACE UNIQUE  INDEX "INDEX24143319341500" ON "ROOT"."ACCESS_STATISTICS"("AS_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ROOT"."AUDIT_INFO"
(
"AUDIT_INFO_ID" VARCHAR(32) NOT NULL,
"LOGIN_ID" VARCHAR(32),
"IP" VARCHAR(32),
"OPER_TYPE" VARCHAR(32),
"OPER_MESSAGE" VARCHAR(1000),
"STATUS" VARCHAR(10),
"OPERATE_DATE" VARCHAR(32),
"REQUEST_DATA" TEXT,
"RESPONSE_DATA" TEXT,
"HMAC" VARCHAR(255),
"EXTEND1" INT,
"EXTEND2" VARCHAR(255),
"EXTEND3" TEXT,
NOT CLUSTER PRIMARY KEY("AUDIT_INFO_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."AUDIT_INFO_ID" IS '物理主键';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."EXTEND1" IS '扩展字段1';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."EXTEND2" IS '扩展字段2';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."EXTEND3" IS '扩展字段3';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."HMAC" IS 'hmac值';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."IP" IS '登录IP';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."LOGIN_ID" IS '用户名';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."OPER_MESSAGE" IS '操作详情';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."OPER_TYPE" IS '操作类型,登录、导入、修改、注销、新增、审核、注册、删除';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."OPERATE_DATE" IS '操作时间，yyyy-mm-dd H24:MM:dd';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."REQUEST_DATA" IS '请求参数';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."RESPONSE_DATA" IS '响应数据';
COMMENT ON COLUMN "ROOT"."AUDIT_INFO"."STATUS" IS '结果，成功、失败';


CREATE OR REPLACE UNIQUE  INDEX "INDEX24142735748300" ON "ROOT"."AUDIT_INFO"("AUDIT_INFO_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ROOT"."BUS_LOG_COUNT"
(
"BUS_LOG_ID" VARCHAR(32) NOT NULL,
"LOGIN_ID" VARCHAR(32),
"OPER_TYPE" VARCHAR(32) DEFAULT '1',
"OPERATE_DATE" VARCHAR(32),
"BUS_COUNT" BIGINT DEFAULT 0,
"TOTAL_SUCCESS_COUNT" BIGINT DEFAULT 0,
"TOTAL_FAIL_COUNT" BIGINT DEFAULT 0,
"EXTEND1" INT DEFAULT 0,
"EXTEND2" VARCHAR(255),
"EXTEND3" TEXT,
NOT CLUSTER PRIMARY KEY("BUS_LOG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."BUS_COUNT" IS '业务总次数';
COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."BUS_LOG_ID" IS '物理主键';
COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."EXTEND1" IS '扩展字段1';
COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."EXTEND2" IS '扩展字段2';
COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."EXTEND3" IS '扩展字段3';
COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."LOGIN_ID" IS '企业id/租户id';
COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."OPER_TYPE" IS '操作类型,签名、验签、加密、解密';
COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."OPERATE_DATE" IS '操作时间，yyyy-mm-dd H24:MM:dd';
COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."TOTAL_FAIL_COUNT" IS '业务总失败次数';
COMMENT ON COLUMN "ROOT"."BUS_LOG_COUNT"."TOTAL_SUCCESS_COUNT" IS '业务总成功次数';


CREATE OR REPLACE UNIQUE  INDEX "INDEX24142211284300" ON "ROOT"."BUS_LOG_COUNT"("BUS_LOG_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ROOT"."COMPANY_INFO"
(
"COMPANY_INFO_ID" VARCHAR(32) NOT NULL,
"COMP_ID" VARCHAR(32),
"TENANT_ID" VARCHAR(100),
"TENANT_NAME" VARCHAR(500),
"COMP_STATUS" CHAR(1) DEFAULT '1',
"NEED_INSPECT" CHAR(1),
"SECRET_KEY" VARCHAR(4000),
"APP_ID" VARCHAR(64),
"UD_COUNT" INT,
"LOGIN_MODE" INT,
"USER_QUOTA" VARCHAR(255),
"UPDATE_DATE" VARCHAR(32),
"CREATE_DATE" VARCHAR(32),
"EXTEND1" INT,
"EXTEND2" VARCHAR(255),
"EXTEND3" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("COMPANY_INFO_ID"),
CONSTRAINT "IDX_COMPANYINFO_COMID" UNIQUE("COMP_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."COMPANY_INFO" IS '租户信息表';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."APP_ID" IS '申请使用SDK对应应用的ID';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."COMP_ID" IS '租户号';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."COMP_STATUS" IS '状态  0：冻结，1：可用';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."COMPANY_INFO_ID" IS '主键';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."CREATE_DATE" IS '创建日期';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."LOGIN_MODE" IS '登录方式，0:代表密码登录，1：代表ukey登录';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."NEED_INSPECT" IS '是否需要进行审批 0不需要，1需要';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."SECRET_KEY" IS '认证密钥（企业应用内置的SECRET_KEY用于认证请求是否有效，或进行使用次数统计的操作）';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."TENANT_ID" IS '租户编码（web平台侧）';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."TENANT_NAME" IS '租户名称（web平台侧）';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."UD_COUNT" IS '用户设备数量';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."UPDATE_DATE" IS '更新日期';
COMMENT ON COLUMN "ROOT"."COMPANY_INFO"."USER_QUOTA" IS '用户数量限额，密文';


CREATE OR REPLACE UNIQUE  INDEX "INDEX24141569368400" ON "ROOT"."COMPANY_INFO"("COMPANY_INFO_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ROOT"."SEC_AUTH_MODE"
(
"ID" VARCHAR(64) NOT NULL,
"AUTH_MODE_CN_NAME" VARCHAR(64) DEFAULT '' NOT NULL,
"AUTH_MODE_EN_NAME" VARCHAR(64) DEFAULT '' NOT NULL,
"INIT_STATUS" TINYINT DEFAULT 0 NOT NULL,
"ROUTE_PATH" VARCHAR(100) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_AUTH_MODE" IS '认证模式';
COMMENT ON COLUMN "ROOT"."SEC_AUTH_MODE"."AUTH_MODE_CN_NAME" IS '认证模式中文名称';
COMMENT ON COLUMN "ROOT"."SEC_AUTH_MODE"."AUTH_MODE_EN_NAME" IS '认证模式英文名称';
COMMENT ON COLUMN "ROOT"."SEC_AUTH_MODE"."INIT_STATUS" IS '初始化状态0：未初始化，1：已初始化';
COMMENT ON COLUMN "ROOT"."SEC_AUTH_MODE"."ROUTE_PATH" IS '页面路由';


CREATE TABLE "ROOT"."SEC_BK_TYPE_CONF"
(
"ID" VARCHAR(64) NOT NULL,
"BACKUP_TYPE" VARCHAR(128) DEFAULT '' NOT NULL,
"BACKUP_PATH" VARCHAR(255) DEFAULT '' NOT NULL,
"RECOVER_PATH" VARCHAR(255) DEFAULT '' NOT NULL,
"UPLOAD_FILE_PATH" VARCHAR(255) DEFAULT '' NOT NULL,
"UKEY_QTY" TINYINT DEFAULT 0 NOT NULL,
"IS_CLOUD" TINYINT DEFAULT 0 NOT NULL,
"CLOUD_TYPE" TINYINT DEFAULT 0 NOT NULL,
"CLOUD_URL" VARCHAR(255) DEFAULT '' NOT NULL,
"CLOUD_USER_NAME" VARCHAR(255),
"CLOUD_AUTH" VARCHAR(255),
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
"BK_TYPE_MODE" TINYINT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "UIDX_BACKUP_TYPE" UNIQUE("BACKUP_TYPE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_BK_TYPE_CONF" IS '备份类型配置';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."BACKUP_PATH" IS '备份文件目录';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."BACKUP_TYPE" IS '备份类型（唯一）';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."BK_TYPE_MODE" IS '备份类型模式 0新组合模式 1老的单独备份模式';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."CLOUD_AUTH" IS '口令';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."CLOUD_TYPE" IS '远程同步类型 0为SMB 1为FTP';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."CLOUD_URL" IS '远程服务器地址';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."CLOUD_USER_NAME" IS '用户名';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."ID" IS '主键';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."IS_CLOUD" IS '是否需要将备份文件上传到远程服务器';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."RECOVER_PATH" IS '恢复文件的保存位置';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."UKEY_QTY" IS 'Ukey备份时，需要插入的Ukey数量';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."UPDATE_DATE" IS '更新时间';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_CONF"."UPLOAD_FILE_PATH" IS '恢复文件上传位置';


CREATE TABLE "ROOT"."SEC_BK_TYPE_STRATEGY"
(
"ID" VARCHAR(64) NOT NULL,
"BACKUP_TYPE" VARCHAR(128) DEFAULT '' NOT NULL,
"STRATEGY_NAME" VARCHAR(128) DEFAULT '' NOT NULL,
"SERVICE_PORT" INT DEFAULT 0 NOT NULL,
"BACKUP_API" VARCHAR(255) DEFAULT '' NOT NULL,
"RECOVER_API" VARCHAR(255) DEFAULT '' NOT NULL,
"ROLLBACK_API" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
"RECOVER_SORT" TINYINT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_BK_TYPE_STRATEGY" IS '备份类型策略';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."BACKUP_API" IS '备份接口的服务名';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."BACKUP_TYPE" IS '备份类型';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."ID" IS '主键';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."RECOVER_API" IS '恢复接口的服务名';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."RECOVER_SORT" IS '恢复顺序';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."ROLLBACK_API" IS '回复失败回滚接口';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."SERVICE_PORT" IS '接口的服务端口';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."STRATEGY_NAME" IS '策略名称（唯一）';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_BK_TYPE_STRATEGY"."UPDATE_DATE" IS '更新时间';


CREATE OR REPLACE  INDEX "IDX_BACKUP_TYPE" ON "ROOT"."SEC_BK_TYPE_STRATEGY"("BACKUP_TYPE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ROOT"."SEC_BKTYPE_MAPPING"
(
"ID" VARCHAR(64) NOT NULL,
"BACKUP_TYPE" VARCHAR(128) DEFAULT '' NOT NULL,
"SERVICE_PORT" INT DEFAULT 0 NOT NULL,
"BACKUP_API" VARCHAR(255) DEFAULT '' NOT NULL,
"RECOVER_API" VARCHAR(255) DEFAULT '' NOT NULL,
"RECOVER_PATH" VARCHAR(255) DEFAULT '' NOT NULL,
"DESCRIPTION" VARCHAR(255) DEFAULT '' NOT NULL,
"UKEY_QTY" TINYINT DEFAULT 0 NOT NULL,
"IS_CLOUD" TINYINT DEFAULT 0 NOT NULL,
"CLOUD_URL" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("BACKUP_TYPE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_BKTYPE_MAPPING" IS '备份类型';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."BACKUP_API" IS '备份接口的服务名';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."BACKUP_TYPE" IS '备份类型（唯一）';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."CLOUD_URL" IS '远程服务器地址';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."ID" IS '主键';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."IS_CLOUD" IS '是否需要将备份文件上传到远程服务器';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."RECOVER_API" IS '恢复接口的服务名';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."RECOVER_PATH" IS '恢复文件的保存位置';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."SERVICE_PORT" IS '接口的服务端口';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."UKEY_QTY" IS 'Ukey备份时，需要插入的Ukey数量';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_BKTYPE_MAPPING"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_COM_CONFIG"
(
"ID" VARCHAR(64) NOT NULL,
"CONFIG_CODE" VARCHAR(50) DEFAULT '' NOT NULL,
"CONFIG_CN_NAME" VARCHAR(100) DEFAULT '' NOT NULL,
"CONFIG_EN_NAME" VARCHAR(100) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_COM_CONFIG" IS '配置分组';
COMMENT ON COLUMN "ROOT"."SEC_COM_CONFIG"."CONFIG_CN_NAME" IS '配置中文名称';
COMMENT ON COLUMN "ROOT"."SEC_COM_CONFIG"."CONFIG_CODE" IS '配置编码';
COMMENT ON COLUMN "ROOT"."SEC_COM_CONFIG"."CONFIG_EN_NAME" IS '配置英文名称';
COMMENT ON COLUMN "ROOT"."SEC_COM_CONFIG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_COM_CONFIG"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_COM_CONFIG"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_COM_CONFIG"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_COM_CONFIG"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_COM_CONFIG"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_COM_ITEM_CFG_REC"
(
"ID" VARCHAR(64) NOT NULL,
"CONFIG_CODE" VARCHAR(50) DEFAULT '' NOT NULL,
"ITEM_CONFIG_CODE" VARCHAR(50) DEFAULT '' NOT NULL,
"ITEM_CONFIG_VALUE" VARCHAR(300) DEFAULT '' NOT NULL,
"OPERATOR" VARCHAR(64) DEFAULT '' NOT NULL,
"OPER_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_COM_ITEM_CFG_REC" IS '配置修改记录';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CFG_REC"."CONFIG_CODE" IS '配置编码';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CFG_REC"."ITEM_CONFIG_CODE" IS '配置编码';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CFG_REC"."ITEM_CONFIG_VALUE" IS '配置值';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CFG_REC"."OPER_DATE" IS '操作时间';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CFG_REC"."OPERATOR" IS '操作人';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CFG_REC"."REMARK" IS '备注';


CREATE TABLE "ROOT"."SEC_COM_ITEM_CONFIG"
(
"ID" VARCHAR(64) NOT NULL,
"CONFIG_CODE" VARCHAR(50) DEFAULT '' NOT NULL,
"ITEM_CONFIG_CODE" VARCHAR(50) DEFAULT '' NOT NULL,
"ITEM_CONFIG_CN_NAME" VARCHAR(100) DEFAULT '' NOT NULL,
"ITEM_CONFIG_EN_NAME" VARCHAR(100) DEFAULT '' NOT NULL,
"ITEM_CONFIG_VALUE" VARCHAR(100) DEFAULT '' NOT NULL,
"CHECK_RULE" VARCHAR(200) DEFAULT '' NOT NULL,
"FLAG_IMPORT" TINYINT DEFAULT 0 NOT NULL,
"FLAG_HIDDEN" TINYINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"DESC_CN" VARCHAR(256) DEFAULT '' NOT NULL,
"DESC_EN" VARCHAR(256) DEFAULT '' NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_COM_ITEM_CONFIG" IS '初始化流程配置';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."CHECK_RULE" IS '配置规则校验';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."CONFIG_CODE" IS '配置编码';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."DESC_CN" IS '中文描述';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."DESC_EN" IS '英文描述';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."FLAG_HIDDEN" IS '是否隐藏0否1是';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."FLAG_IMPORT" IS '是否重要配置0否1是重要配置不可编辑';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."ITEM_CONFIG_CN_NAME" IS '配置中文名称';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."ITEM_CONFIG_CODE" IS '配置编码';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."ITEM_CONFIG_EN_NAME" IS '配置英文名称';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."ITEM_CONFIG_VALUE" IS '配置值';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_COM_ITEM_CONFIG"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_DICT"
(
"ID" VARCHAR(64) NOT NULL,
"TYPE_CODE" VARCHAR(100) DEFAULT '' NOT NULL,
"CODE" VARCHAR(100) DEFAULT '' NOT NULL,
"LANG" VARCHAR(200) DEFAULT '' NOT NULL,
"NAME" VARCHAR(200) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_DICT" IS '字典配置表';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."CODE" IS '字典编码';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."LANG" IS '语言环境';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."NAME" IS '字典名称';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."TYPE_CODE" IS '类型编码';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_DICT"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_DICT_TYPE"
(
"ID" VARCHAR(64) NOT NULL,
"CODE" VARCHAR(100) DEFAULT '' NOT NULL,
"NAME" VARCHAR(200) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "ROOT"."SEC_DICT_TYPE"."CODE" IS '字典类型';
COMMENT ON COLUMN "ROOT"."SEC_DICT_TYPE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_DICT_TYPE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_DICT_TYPE"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_DICT_TYPE"."NAME" IS '英文功能描述';
COMMENT ON COLUMN "ROOT"."SEC_DICT_TYPE"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_DICT_TYPE"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_DICT_TYPE"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_EXT_ROLE_MAPPING"
(
"ID" VARCHAR(64) NOT NULL,
"SOURCE_ROLE_CODE" VARCHAR(64) DEFAULT '' NOT NULL,
"TARGET_ROLE_CODE" VARCHAR(64) DEFAULT '' NOT NULL,
"BUSINESS_TYPE" TINYINT DEFAULT 1 NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_EXT_ROLE_MAPPING" IS '角色映射表';
COMMENT ON COLUMN "ROOT"."SEC_EXT_ROLE_MAPPING"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_EXT_ROLE_MAPPING"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_EXT_ROLE_MAPPING"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_EXT_ROLE_MAPPING"."SOURCE_ROLE_CODE" IS '对接系统的角色编码';
COMMENT ON COLUMN "ROOT"."SEC_EXT_ROLE_MAPPING"."TARGET_ROLE_CODE" IS '映射到web平台自己的角色编码';
COMMENT ON COLUMN "ROOT"."SEC_EXT_ROLE_MAPPING"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_EXT_ROLE_MAPPING"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_INIT_NODE"
(
"ID" VARCHAR(64) NOT NULL,
"INIT_NODE_CN_NAME" VARCHAR(50) DEFAULT '' NOT NULL,
"INIT_NODE_EN_NAME" VARCHAR(50) DEFAULT '' NOT NULL,
"INIT_NODE_CODE" VARCHAR(50) DEFAULT '' NOT NULL,
"ROUTE_PATH" VARCHAR(100) DEFAULT '' NOT NULL,
"ROUTE_URL" VARCHAR(100) DEFAULT '' NOT NULL,
"ATTACHMENT" VARCHAR(256) DEFAULT '' NOT NULL,
"SORT_NO" TINYINT DEFAULT 0 NOT NULL,
"CUR_NODE" TINYINT DEFAULT 0 NOT NULL,
"INIT_STATUS" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_INIT_NODE" IS '初始化流程配置';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."ATTACHMENT" IS '附件';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."CUR_NODE" IS '是否当前节点 0：否，1：是';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."INIT_NODE_CN_NAME" IS '流程中文名称';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."INIT_NODE_CODE" IS '流程编码';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."INIT_NODE_EN_NAME" IS '流程英文名称';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."INIT_STATUS" IS '初始化状态0：未初始化，1：已初始化';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."ROUTE_PATH" IS '公共路由';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."ROUTE_URL" IS '业务路由';
COMMENT ON COLUMN "ROOT"."SEC_INIT_NODE"."SORT_NO" IS '序号，用作页面展示排序用';


CREATE TABLE "ROOT"."SEC_LOG_AUDIT"
(
"ID" VARCHAR(64) DEFAULT '' NOT NULL,
"SERVER_CODE" VARCHAR(128) DEFAULT '' NOT NULL,
"USER_ID" VARCHAR(64) DEFAULT '' NOT NULL,
"SERVER_ADDRESS" VARCHAR(128) DEFAULT '' NOT NULL,
"CLIENT_ADDRESS" VARCHAR(128) DEFAULT '' NOT NULL,
"ACTION" VARCHAR(128) DEFAULT '' NOT NULL,
"RESULT" TINYINT DEFAULT 0 NOT NULL,
"TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"INPUT_PARAM" VARCHAR(2048) DEFAULT '' NOT NULL,
"OUTPUT_PARAM" VARCHAR(2048) DEFAULT '' NOT NULL,
"HASH_CODE" VARCHAR(128) DEFAULT '' NOT NULL,
"AUDIT_RESULT" TINYINT DEFAULT 0 NOT NULL,
"DEVICE_ID" VARCHAR(100) DEFAULT '' NOT NULL,
"TENANT_CODE" VARCHAR(100) DEFAULT '' NOT NULL,
"RESULT_CN_MSG" VARCHAR(500) DEFAULT '' NOT NULL,
"RESULT_EN_MSG" VARCHAR(500) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_LOG_AUDIT" IS '操作日志';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."ACTION" IS '操作类型';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."AUDIT_RESULT" IS '审计结果 0-未审计 1-已审计';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."CLIENT_ADDRESS" IS '客户端IP地址';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."DEVICE_ID" IS '设备唯一标识';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."HASH_CODE" IS '签名结果';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."ID" IS '主键';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."INPUT_PARAM" IS '请求参数';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."OUTPUT_PARAM" IS '相应结果';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."RESULT" IS '操作结果 0-失败 1-成功';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."RESULT_CN_MSG" IS '操作对象-中文';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."RESULT_EN_MSG" IS '操作对象-英文';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."SERVER_ADDRESS" IS '服务端IP地址';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."SERVER_CODE" IS '服务编码';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."TENANT_CODE" IS '租户编码';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."TIME" IS '操作时间';
COMMENT ON COLUMN "ROOT"."SEC_LOG_AUDIT"."USER_ID" IS '用户名';


CREATE TABLE "ROOT"."SEC_LOG_SYSLOG"
(
"ID" VARCHAR(64) DEFAULT '' NOT NULL,
"SERVER_CODE" VARCHAR(128) DEFAULT '' NOT NULL,
"CA_ID" VARCHAR(128) DEFAULT '' NOT NULL,
"REMOTE_SERVER" VARCHAR(128) DEFAULT '' NOT NULL,
"REMOTE_PORT" BIGINT DEFAULT 0 NOT NULL,
"TRANSPORT" TINYINT DEFAULT 0 NOT NULL,
"LOG_FILE_NAME" VARCHAR(128) DEFAULT '' NOT NULL,
"CA_FILE_HASH" VARCHAR(128) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_LOG_SYSLOG" IS 'sylogr日志配置';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."CA_FILE_HASH" IS 'CA证书Hash值';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."CA_ID" IS 'CA 证书编码';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."ID" IS '主键';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."LOG_FILE_NAME" IS '服务日志名称';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."REMOTE_PORT" IS '目标服务端口';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."REMOTE_SERVER" IS '目标服务IP地址';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."SERVER_CODE" IS '服务编码';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."TRANSPORT" IS '传输协议 0-tcp 1-udp 2-ssl';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_LOG_SYSLOG"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_MENU"
(
"ID" VARCHAR(64) NOT NULL,
"MENU_CODE" VARCHAR(64) DEFAULT '' NOT NULL,
"MENU_NAME" VARCHAR(100) DEFAULT '' NOT NULL,
"MENU_NAME_EN" VARCHAR(100) DEFAULT '' NOT NULL,
"MENU_CSS" VARCHAR(200) DEFAULT '' NOT NULL,
"MENU_INIT_CERT" VARCHAR(50) DEFAULT '' NOT NULL,
"MENU_TYPE" TINYINT DEFAULT 0 NOT NULL,
"MENU_PID" VARCHAR(64) DEFAULT '' NOT NULL,
"MENU_URL" VARCHAR(200) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
"MENU_ALWAYS_SHOW" TINYINT DEFAULT 0 NOT NULL,
"MENU_COMP" VARCHAR(100) DEFAULT '' NOT NULL,
"MENU_HIDDEN" TINYINT DEFAULT 0 NOT NULL,
"MENU_CACHE" TINYINT DEFAULT 1 NOT NULL,
"MENU_LINK" VARCHAR(100) DEFAULT '' NOT NULL,
"MENU_TITLE" VARCHAR(100) DEFAULT '' NOT NULL,
"MENU_QUERY" VARCHAR(255) DEFAULT '' NOT NULL,
"MENU_MARK" VARCHAR(100) DEFAULT '' NOT NULL,
"MENU_ACTIVE" VARCHAR(50) DEFAULT '' NOT NULL,
"SERVER_CODE" VARCHAR(100) DEFAULT '' NOT NULL,
"MENU_SORT" INT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_MENU" IS '菜单按钮配置表';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."ID" IS '用户唯一标识';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_ALWAYS_SHOW" IS '0为false 1为true级菜单是否展开展示';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_CACHE" IS 'noCache  0是false  1true（页面是否刷新）';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_CODE" IS '菜单编码';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_COMP" IS '具体页面文件地址（1级配置layout2级具体地址 业务2级配置iframeCom/index）';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_CSS" IS '菜单样式(一级菜单的icon)';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_HIDDEN" IS 'hidden    0是false  1true（作用于三级菜单隐藏）';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_INIT_CERT" IS '（得去掉）';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_LINK" IS 'link';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_MARK" IS '菜单标识：主要是crud按钮权限标识';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_NAME" IS '菜单名称';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_NAME_EN" IS '英文菜单名字';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_PID" IS '菜单父节点';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_QUERY" IS '当url为外部的连接时，此处传json格式的信息';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_SORT" IS '菜单顺序';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_TITLE" IS '路由名称';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_TYPE" IS '菜单类型0菜单1按钮2是首页专用类型3是三级弹窗';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."MENU_URL" IS '菜单路由地址';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."SERVER_CODE" IS '注册服务来源';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "ROOT"."SEC_MENU"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_MENU_FUNC"
(
"ID" VARCHAR(64) NOT NULL,
"MENU_CODE" VARCHAR(100) DEFAULT '' NOT NULL,
"FUNC_URL" VARCHAR(100) DEFAULT '' NOT NULL,
"FLAG_COMMON" TINYINT DEFAULT 0,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
"FLAG_DEL" TINYINT DEFAULT 0,
"REMARK" VARCHAR(256) DEFAULT '',
"SERVER_CODE" VARCHAR(100) DEFAULT '',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_MENU_FUNC" IS '菜单功能请求配置';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."FLAG_COMMON" IS '公共请求1是,0否';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."FUNC_URL" IS '流程英文名称';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."MENU_CODE" IS '菜单编码';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."SERVER_CODE" IS '注册服务来源';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_MENU_FUNC"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_REC_LOG_FUNC"
(
"ID" VARCHAR(64) NOT NULL,
"FUNC_CODE" VARCHAR(100) DEFAULT '' NOT NULL,
"FUNC_URL" VARCHAR(100) DEFAULT '' NOT NULL,
"FUNC_CN_NAME" VARCHAR(200) DEFAULT '' NOT NULL,
"FUNC_EN_NAME" VARCHAR(200) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
"SERVER_CODE" VARCHAR(100) DEFAULT '',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_REC_LOG_FUNC" IS '操作日志接口配置表';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."FUNC_CN_NAME" IS '中文功能描述';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."FUNC_CODE" IS '功能编码';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."FUNC_EN_NAME" IS '英文功能描述';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."FUNC_URL" IS '接口地址';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."SERVER_CODE" IS '注册服务来源';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_REC_LOG_FUNC"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_ROLE"
(
"ID" VARCHAR(64) NOT NULL,
"ROLE_CODE" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
"FLAG_INITIAL_ROLE" TINYINT DEFAULT 0 NOT NULL,
"ENABLE_DEL_USER" TINYINT DEFAULT 1 NOT NULL,
"ROW_SIGN" VARCHAR(100) DEFAULT '' NOT NULL,
"ROLE_TYPE" TINYINT DEFAULT 1 NOT NULL,
"ROLE_PID" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_ROLE" IS '角色表';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."ENABLE_DEL_USER" IS '对应角色用户是否支持删除 0不支持删除 1允许删除';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."FLAG_INITIAL_ROLE" IS '是否内置角色 0否1是';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."ID" IS 'id';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."ROLE_CODE" IS '角色编码唯一';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."ROLE_PID" IS '上级角色id';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."ROLE_TYPE" IS '角色类型 1系统角色 2租户角色';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."ROW_SIGN" IS '表中数据签名';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "ROOT"."SEC_ROLE"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_ROLE_MENU"
(
"ID" VARCHAR(64) NOT NULL,
"ROLE_CODE" VARCHAR(64) DEFAULT '' NOT NULL,
"MENU_CODE" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
"ROW_SIGN" VARCHAR(100) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_ROLE_MENU" IS '角色菜单对照表';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."ID" IS '用户唯一标识';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."MENU_CODE" IS '菜单编码';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."ROLE_CODE" IS '角色编码';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."ROW_SIGN" IS '表中数据签名';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "ROOT"."SEC_ROLE_MENU"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_ROOT_CA"
(
"ID" VARCHAR(64) NOT NULL,
"CERT_TYPE" VARCHAR(255) DEFAULT '' NOT NULL,
"CUSTOMER_CODE" VARCHAR(255) DEFAULT '' NOT NULL,
"ENCRYPT_CERT" TEXT,
"END_TIME" VARCHAR(255) DEFAULT '' NOT NULL,
"HAS_HALG" VARCHAR(255) DEFAULT '' NOT NULL,
"ISSUER" VARCHAR(255) DEFAULT '' NOT NULL,
"PUBLIC_KEY" TEXT,
"SERIAL_NUMBER" VARCHAR(255) DEFAULT '' NOT NULL,
"SIGN_ALG" VARCHAR(255) DEFAULT '' NOT NULL,
"START_TIME" VARCHAR(255) DEFAULT '' NOT NULL,
"VERIFY_CERT" TEXT,
"VERSION" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_ROOT_CA" IS '根证书';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."CERT_TYPE" IS '证书类型（X.509）';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."CUSTOMER_CODE" IS '客户系统编号';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."ENCRYPT_CERT" IS '加密证书（base64编码）';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."END_TIME" IS '证书过期时间';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."HAS_HALG" IS '签名哈希算法';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."ISSUER" IS '颁发着';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."PUBLIC_KEY" IS '公钥';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."SERIAL_NUMBER" IS '序列号';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."SIGN_ALG" IS '签名算法';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."UPDATE_DATE" IS '更新时间';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."VERIFY_CERT" IS '验签证书（base64编码）';
COMMENT ON COLUMN "ROOT"."SEC_ROOT_CA"."VERSION" IS '版本';


CREATE TABLE "ROOT"."SEC_SERVER_BASE"
(
"ID" VARCHAR(64) NOT NULL,
"SERVER_NAME" VARCHAR(64) DEFAULT '' NOT NULL,
"SERVER_CODE" VARCHAR(64) DEFAULT '' NOT NULL,
"VERSION" VARCHAR(50) DEFAULT '' NOT NULL,
"SERVER_LOG_PATH" VARCHAR(100) DEFAULT '' NOT NULL,
"SERVER_PORT" VARCHAR(10) DEFAULT '' NOT NULL,
"LOG_MANAGE_URL" VARCHAR(255) DEFAULT '' NOT NULL,
"LOG_QUERY_URL" VARCHAR(255) DEFAULT '' NOT NULL,
"FLAG_LOG_CONFIG" TINYINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_SERVER_BASE" IS '服务基础配置表';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."FLAG_LOG_CONFIG" IS '是否需要日志配置0需要1不需要';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."ID" IS '服务id';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."LOG_MANAGE_URL" IS '服务日志管理接口地址';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."LOG_QUERY_URL" IS '服务日志配置查询接口地址';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."SERVER_CODE" IS '服务编码';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."SERVER_LOG_PATH" IS '服务日志地址';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."SERVER_NAME" IS '服务名称';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."SERVER_PORT" IS '服务端口';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."UPDATE_DATE" IS '更新时间';
COMMENT ON COLUMN "ROOT"."SEC_SERVER_BASE"."VERSION" IS '服务当前版本';


CREATE TABLE "ROOT"."SEC_SSL_CA"
(
"ID" VARCHAR(64) NOT NULL,
"CA_NAME" VARCHAR(200) NOT NULL,
"KEY_ALGORITHM" VARCHAR(11) NOT NULL,
"KEY_SIZE" INT NOT NULL,
"CERTIFICATE_ISSUER" VARCHAR(3900) DEFAULT '' NOT NULL,
"CERTIFICATE_SUBJECT" VARCHAR(3900) DEFAULT '' NOT NULL,
"START_DATE" TIMESTAMP(0) NOT NULL,
"EXPIRATION" TIMESTAMP(0) NOT NULL,
"CERTIFICATE_STATUS" INT NOT NULL,
"CERTIFICATE" CLOB NOT NULL,
"ENCPRIVATEKEY" CLOB,
"CERTIFICATE_TYPE" INT NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_SSL_CA" IS 'ca管理';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."CA_NAME" IS 'ca名称';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."CERTIFICATE" IS '证书内容';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."CERTIFICATE_ISSUER" IS '签发者主题';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."CERTIFICATE_STATUS" IS '证书状态';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."CERTIFICATE_SUBJECT" IS '使用者主题';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."CERTIFICATE_TYPE" IS '证书类型（0：自签   1 三方）';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."ENCPRIVATEKEY" IS '私钥密文';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."EXPIRATION" IS '证书有效结束日期';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."KEY_ALGORITHM" IS '证书公钥算法';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."KEY_SIZE" IS '证书公钥长度';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."START_DATE" IS '证书有效开始日期';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CA"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_SSL_CERTIFICATE"
(
"ID" VARCHAR(64) NOT NULL,
"CA_ID" VARCHAR(64) DEFAULT '' NOT NULL,
"CERTIFICATE_SN" VARCHAR(64) DEFAULT '' NOT NULL,
"CERTIFICATE_NAME" VARCHAR(200) DEFAULT '' NOT NULL,
"KEY_SIZE" INT NOT NULL,
"KEY_ALGORITHM" VARCHAR(11) NOT NULL,
"CERTIFICATE_ISSUER" VARCHAR(3072) DEFAULT '' NOT NULL,
"CERTIFICATE_SUBJECT" VARCHAR(3072) DEFAULT '' NOT NULL,
"START_DATE" TIMESTAMP(0),
"EXPIRATION" TIMESTAMP(0),
"CERTIFICATE_STATUS" INT DEFAULT 0 NOT NULL,
"PURPOSE" INT DEFAULT 0 NOT NULL,
"CERTIFICATE" CLOB,
"ENCPRIVATEKEY" CLOB,
"KEYSTORE_TYPE" VARCHAR(96) DEFAULT '' NOT NULL,
"KEYSTORE" CLOB,
"REVOCATION_DATE" TIMESTAMP(0),
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_SSL_CERTIFICATE" IS '证书管理';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."CA_ID" IS 'ca id';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."CERTIFICATE" IS '证书内容';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."CERTIFICATE_ISSUER" IS '签发者主题';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."CERTIFICATE_NAME" IS '证书名称';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."CERTIFICATE_SN" IS '证书序列号';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."CERTIFICATE_STATUS" IS '证书状态';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."CERTIFICATE_SUBJECT" IS '使用者主题';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."ENCPRIVATEKEY" IS '加密私钥';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."EXPIRATION" IS '证书有效结束日期';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."KEY_ALGORITHM" IS '公钥算法';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."KEY_SIZE" IS '公钥长度';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."KEYSTORE" IS 'keystore 保存密钥对';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."KEYSTORE_TYPE" IS 'keystore类型';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."PURPOSE" IS '证书属性：0签名和加密、1签名、2加密';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."START_DATE" IS '证书有效开始日期';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SSL_CERTIFICATE"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_SSL_SIGNED_CERT"
(
"ID" VARCHAR(64) NOT NULL,
"LOCALCAID" VARCHAR(64) NOT NULL,
"CERT_SN" VARCHAR(768) NOT NULL,
"KEY_SIZE" INT NOT NULL,
"CERTIFICATE_ISSUER" VARCHAR(3900) NOT NULL,
"CERTIFICATE_SUBJECT" VARCHAR(3900) NOT NULL,
"STARTDATE" TIMESTAMP(0) NOT NULL,
"EXPIRATION" TIMESTAMP(0) NOT NULL,
"CERTIFICATE_STATUS" INT NOT NULL,
"CERTIFICATE" CLOB NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_SSL_SIGNED_CERT" IS '历史签名证书';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."CERT_SN" IS '证书序列号';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."CERTIFICATE" IS '证书内容';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."CERTIFICATE_ISSUER" IS '证书颁发者主题';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."CERTIFICATE_STATUS" IS '证书状态';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."CERTIFICATE_SUBJECT" IS '证书使用者主题';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."EXPIRATION" IS '证书有效截止日期';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."KEY_SIZE" IS '密钥长度';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."LOCALCAID" IS '自签CA ID';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."STARTDATE" IS '证书有效开始日期';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SSL_SIGNED_CERT"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_SYS_IMAGE"
(
"ID" VARCHAR(64) NOT NULL,
"IMAGE_TYPE" VARCHAR(50) DEFAULT '' NOT NULL,
"IMAGE_CODE" VARCHAR(50) DEFAULT '' NOT NULL,
"THEME_ID" VARCHAR(64) DEFAULT '' NOT NULL,
"IMAGE_INFO" CLOB,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_SYS_IMAGE" IS '系统图片';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."ID" IS '主键';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."IMAGE_CODE" IS '图片编码';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."IMAGE_INFO" IS '图片内容';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."IMAGE_TYPE" IS '图片类型如jpg、png';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."THEME_ID" IS '所属主题id';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_SYS_IMAGE"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_TENANT"
(
"ID" VARCHAR(64) NOT NULL,
"CODE" VARCHAR(100) DEFAULT '' NOT NULL,
"NAME" VARCHAR(256) DEFAULT '' NOT NULL,
"STATUS" TINYINT DEFAULT 0 NOT NULL,
"flag_freeze" TINYINT DEFAULT 1 NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "SEC_TENANT_CODE_UINDEX" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_TENANT" IS '租户信息表';
COMMENT ON COLUMN "ROOT"."SEC_TENANT"."CODE" IS '租户编码';
COMMENT ON COLUMN "ROOT"."SEC_TENANT"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_TENANT"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_TENANT"."flag_freeze" IS '是否冻结 1未冻结 0冻结';
COMMENT ON COLUMN "ROOT"."SEC_TENANT"."NAME" IS '租户名称';
COMMENT ON COLUMN "ROOT"."SEC_TENANT"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_TENANT"."STATUS" IS '流程状态 0.已创建 1.已初始化人员';
COMMENT ON COLUMN "ROOT"."SEC_TENANT"."UPDATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_TENANT"."UPDATE_DATE" IS '更新时间';


CREATE TABLE "ROOT"."SEC_THEME"
(
"ID" VARCHAR(64) NOT NULL,
"THEME_NAME_ZH" VARCHAR(100) DEFAULT '' NOT NULL,
"THEME_NAME_EN" VARCHAR(100) DEFAULT '' NOT NULL,
"WEB_TITLE" VARCHAR(64) DEFAULT '' NOT NULL,
"TAGS_VIEW" TINYINT DEFAULT 1 NOT NULL,
"SIDEBAR_LOGO" TINYINT DEFAULT 1 NOT NULL,
"DYNAMIC_TITLE" TINYINT DEFAULT 0 NOT NULL,
"THEME" VARCHAR(32) DEFAULT '' NOT NULL,
"SIDE_THEME" VARCHAR(32) DEFAULT '' NOT NULL,
"MENU_COLOR_CUS" VARCHAR(32) DEFAULT '' NOT NULL,
"MENU_BK_CUS" VARCHAR(32) DEFAULT '' NOT NULL,
"MENU_COLOR_ACT_CUS" VARCHAR(32) DEFAULT '' NOT NULL,
"SUB_MENU_BK_CUS" VARCHAR(32) DEFAULT '' NOT NULL,
"SUB_MENU_BK_ACT_CUS" VARCHAR(32) DEFAULT '' NOT NULL,
"SUB_MENU_HOVER_CUS" VARCHAR(32) DEFAULT '' NOT NULL,
"TOP_BK_CUS" VARCHAR(32) DEFAULT '' NOT NULL,
"TOP_SVG_CUS" VARCHAR(32) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_THEME" IS '主题样式表';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."DYNAMIC_TITLE" IS '是否显示动态标题 0不显示 1显示';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."MENU_BK_CUS" IS '背景颜色-主菜单';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."MENU_COLOR_ACT_CUS" IS '菜单文字颜色-高亮';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."MENU_COLOR_CUS" IS '菜单文字颜色';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."SIDE_THEME" IS '侧边栏颜色';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."SIDEBAR_LOGO" IS '是否显示logo 0不显示 1显示';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."SUB_MENU_BK_ACT_CUS" IS '背景颜色-菜单高亮';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."SUB_MENU_BK_CUS" IS '背景颜色-子菜单';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."SUB_MENU_HOVER_CUS" IS '背景颜色-鼠标悬停阴影色';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."TAGS_VIEW" IS '是否显示tagsView 0不显示 1显示';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."THEME" IS '主题色';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."THEME_NAME_EN" IS '主题英文名';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."THEME_NAME_ZH" IS '主题中文名';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."TOP_BK_CUS" IS '顶部导航栏背景色';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."TOP_SVG_CUS" IS '顶部导航栏图标颜色';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."UPDATE_DATE" IS '更新时间';
COMMENT ON COLUMN "ROOT"."SEC_THEME"."WEB_TITLE" IS '网页名称';


CREATE TABLE "ROOT"."SEC_USER"
(
"ID" VARCHAR(64) NOT NULL,
"USER_NAME" VARCHAR(255) DEFAULT '' NOT NULL,
"USER_PWD" VARCHAR(255) DEFAULT '' NOT NULL,
"ENCRY_TYPE" TINYINT DEFAULT 2 NOT NULL,
"USER_CERT" VARCHAR(5000) DEFAULT '' NOT NULL,
"USER_DN" VARCHAR(500) DEFAULT '' NOT NULL,
"USER_UK_NO" VARCHAR(200) DEFAULT '' NOT NULL,
"USER_TEL" VARCHAR(255) DEFAULT '' NOT NULL,
"USER_EMAIL" VARCHAR(255) DEFAULT '' NOT NULL,
"USER_ADDR" VARCHAR(255) DEFAULT '' NOT NULL,
"USER_TYPE" TINYINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
"USER_IDENTITY" VARCHAR(100) DEFAULT '' NOT NULL,
"LOGIN_DATE" TIMESTAMP(0),
"ROW_SIGN" VARCHAR(100) DEFAULT '' NOT NULL,
"TENANT_CODE" VARCHAR(100) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_USER" IS '用户表';
COMMENT ON COLUMN "ROOT"."SEC_USER"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_USER"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_USER"."ENCRY_TYPE" IS '密码传输加密方式：1,base64;2,SM3';
COMMENT ON COLUMN "ROOT"."SEC_USER"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_USER"."ID" IS '用户唯一标识';
COMMENT ON COLUMN "ROOT"."SEC_USER"."LOGIN_DATE" IS '最后登录时间';
COMMENT ON COLUMN "ROOT"."SEC_USER"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_USER"."ROW_SIGN" IS '用户信息签名';
COMMENT ON COLUMN "ROOT"."SEC_USER"."TENANT_CODE" IS '租户编码';
COMMENT ON COLUMN "ROOT"."SEC_USER"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "ROOT"."SEC_USER"."UPDATE_DATE" IS '更新时间';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_ADDR" IS '地址';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_CERT" IS '证书';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_DN" IS 'Dn';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_EMAIL" IS '邮箱';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_IDENTITY" IS '用户身份，用于记录超级管理员和审计员SuperManager\CheckManager';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_NAME" IS '用户登录名';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_PWD" IS '密码(加密后)';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_TEL" IS '电话号码';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_TYPE" IS '用户登录类型:0用户名密码；1UK';
COMMENT ON COLUMN "ROOT"."SEC_USER"."USER_UK_NO" IS 'uk序列号';


CREATE TABLE "ROOT"."SEC_USER_ROLE"
(
"ID" VARCHAR(64) NOT NULL,
"ROLE_CODE" VARCHAR(64) DEFAULT '' NOT NULL,
"USER_ID" VARCHAR(64) DEFAULT '' NOT NULL,
"CREATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_BY" VARCHAR(255) DEFAULT '' NOT NULL,
"UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"FLAG_DEL" TINYINT DEFAULT 0 NOT NULL,
"REMARK" VARCHAR(256) DEFAULT '' NOT NULL,
"ROW_SIGN" VARCHAR(100) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "ROOT"."SEC_USER_ROLE" IS '用户角色对照表';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."FLAG_DEL" IS '删除标识 0正常1删除';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."ID" IS 'id';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."REMARK" IS '备注';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."ROLE_CODE" IS '角色编码';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."ROW_SIGN" IS '表中数据签名';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."UPDATE_DATE" IS '更新时间';
COMMENT ON COLUMN "ROOT"."SEC_USER_ROLE"."USER_ID" IS '用户id';


CREATE TABLE "ROOT"."SEQUENCE_ID"
(
"SEQ_NAME" VARCHAR(50) NOT NULL,
"CURRENT_VAL" INT NOT NULL,
"INCREMENT_VAL" INT DEFAULT 1 NOT NULL,
NOT CLUSTER PRIMARY KEY("SEQ_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "ROOT"."SEQUENCE_ID"."CURRENT_VAL" IS '当前值';
COMMENT ON COLUMN "ROOT"."SEQUENCE_ID"."INCREMENT_VAL" IS '--步长(跨度)';
COMMENT ON COLUMN "ROOT"."SEQUENCE_ID"."SEQ_NAME" IS '序列名称';


CREATE OR REPLACE UNIQUE  INDEX "PRIMARY" ON "ROOT"."SEQUENCE_ID"("SEQ_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

